CREATE TABLE payroll_configs (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                   BIGINT       NOT NULL,
    year                        INT          NOT NULL,
    minimum_wage                NUMERIC(14, 2) NOT NULL,
    transport_subsidy           NUMERIC(14, 2) NOT NULL,
    monthly_work_hours          NUMERIC(6, 2)  NOT NULL,
    normal_daily_hours          NUMERIC(5, 2)  NOT NULL,
    max_daily_extra_hours       NUMERIC(5, 2)  NOT NULL,
    daytime_start               TIME         NOT NULL,
    daytime_end                 TIME         NOT NULL,
    daytime_ot_start            TIME         NOT NULL,
    daytime_ot_end              TIME         NOT NULL,
    night_surcharge_start       TIME         NOT NULL,
    night_surcharge_end         TIME         NOT NULL,
    nocturnal_ot_start          TIME         NOT NULL,
    nocturnal_ot_end            TIME         NOT NULL,
    sunday_ot_start             TIME         NOT NULL,
    sunday_ot_end               TIME         NOT NULL,
    daytime_ot_factor           NUMERIC(5, 2) NOT NULL,
    nocturnal_ot_factor         NUMERIC(5, 2) NOT NULL,
    night_surcharge_factor      NUMERIC(5, 2) NOT NULL,
    sunday_holiday_daytime_ot_factor     NUMERIC(5, 2) NOT NULL,
    sunday_holiday_nocturnal_ot_factor   NUMERIC(5, 2) NOT NULL,
    sunday_holiday_normal_factor         NUMERIC(5, 2) NOT NULL,
    non_billable_rest_minutes   INT          NOT NULL,
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_payroll_config_tenant_year UNIQUE (tenant_id, year)
);

CREATE INDEX idx_payroll_configs_tenant_id ON payroll_configs (tenant_id);

CREATE TABLE holidays (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL,
    holiday_date  DATE         NOT NULL,
    description   VARCHAR(150),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_holiday_tenant_date UNIQUE (tenant_id, holiday_date)
);

CREATE INDEX idx_holidays_tenant_id ON holidays (tenant_id);
CREATE INDEX idx_holidays_tenant_date ON holidays (tenant_id, holiday_date);
