CREATE TABLE employees (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT         NOT NULL,
    user_id         BIGINT,
    first_name      VARCHAR(100)   NOT NULL,
    last_name       VARCHAR(100)   NOT NULL,
    id_type         VARCHAR(20)    NOT NULL,
    id_number       VARCHAR(50)    NOT NULL,
    email           VARCHAR(255)   NOT NULL,
    phone           VARCHAR(20),
    monthly_salary  NUMERIC(14, 2) NOT NULL,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_employee_tenant_id_number UNIQUE (tenant_id, id_number),
    CONSTRAINT uq_employee_tenant_email UNIQUE (tenant_id, email)
);

CREATE INDEX idx_employees_tenant_id ON employees (tenant_id);
CREATE INDEX idx_employees_tenant_id_number ON employees (tenant_id, id_number);
