CREATE TABLE time_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT         NOT NULL,
    employee_id     BIGINT         NOT NULL REFERENCES employees(id),
    work_date       DATE           NOT NULL,
    clock_in        TIMESTAMPTZ    NOT NULL,
    clock_out       TIMESTAMPTZ,
    status          VARCHAR(20)    NOT NULL CHECK (status IN ('OPEN', 'CLOSED', 'INCOMPLETE')),
    corrected       BOOLEAN        NOT NULL DEFAULT FALSE,
    original_clock_in  TIMESTAMPTZ,
    original_clock_out TIMESTAMPTZ,
    correction_reason  VARCHAR(500),
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_time_record_employee_date UNIQUE (tenant_id, employee_id, work_date)
);

CREATE INDEX idx_time_records_tenant_employee_date ON time_records (tenant_id, employee_id, work_date);
CREATE INDEX idx_time_records_tenant_status_date ON time_records (tenant_id, status, work_date);
