CREATE TABLE admin_notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT         NOT NULL,
    notification_type VARCHAR(50)    NOT NULL,
    title             VARCHAR(200)   NOT NULL,
    message           TEXT           NOT NULL,
    payload           JSONB          NOT NULL,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_admin_notifications_tenant_created
    ON admin_notifications (tenant_id, created_at DESC);
